# Generated by Django 5.2 on 2025-04-11 18:26

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumniprofile',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='alumni/default.png', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='students/default.png', max_length=255, null=True, verbose_name='image'),
        ),
    ]
