# Generated by Django 5.1 on 2024-11-13 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumniprofile',
            name='dept',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='dept',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
