# Generated by Django 5.2 on 2025-04-11 19:08

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_alumniprofile_image_alter_studentprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumniprofile',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='default.png', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='default.png', max_length=255, null=True, verbose_name='image'),
        ),
    ]
