# Generated by Django 5.1 on 2024-11-13 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alumniprofile_dept_studentprofile_dept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumniprofile',
            name='dept',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='dept',
            field=models.CharField(max_length=100),
        ),
    ]
