# Generated by Django 5.1 on 2024-11-21 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_alumniprofile_dept_alter_studentprofile_dept'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumniprofile',
            name='image',
            field=models.ImageField(blank=True, default='alumni/default.png', null=True, upload_to='alumni/'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='image',
            field=models.ImageField(blank=True, default='student/default.png', null=True, upload_to='student/'),
        ),
    ]
