# Generated by Django 5.2 on 2025-05-27 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_alumniprofile_image_alter_studentprofile_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumniprofile',
            options={'verbose_name': 'Alumni Profile', 'verbose_name_plural': 'Alumni Profiles'},
        ),
        migrations.AlterModelOptions(
            name='studentprofile',
            options={'verbose_name': 'Student Profile', 'verbose_name_plural': 'Student Profiles'},
        ),
    ]
