# Generated by Django 5.2 on 2025-10-23 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_alumniprofile_university_and_more'),
        ('core', '0009_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumniprofile',
            name='university',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.university'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='university',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.university'),
        ),
    ]
