# Generated by Django 5.2 on 2025-11-04 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_alumniprofile_university_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumniprofile',
            name='contributions_count',
            field=models.IntegerField(default=0),
        ),
    ]
