# Generated by Django 5.2 on 2025-11-08 08:21

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_alumniprofile_contributions_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumniprofile',
            name='transcript',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='transcript'),
        ),
    ]
