# Generated by Django 5.2 on 2025-05-17 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='recipient',
            new_name='receiver',
        ),
    ]
