# Generated by Django 5.2 on 2025-04-11 18:26

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_delete_mymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='events/default.png', max_length=255, null=True, verbose_name='image'),
        ),
    ]
