# Generated by Django 5.2 on 2025-05-27 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_jobs_company_alter_jobs_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'ordering': ['-date', '-time'], 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='jobs',
            options={'ordering': ['-deadline'], 'verbose_name': 'Job', 'verbose_name_plural': 'Jobs'},
        ),
    ]
